name: expense_planner_pro
description: On-demand expense planner with report export feature.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  firebase_core: ^0.5.3
#  firebase_auth: ^0.18.4+1
#  googleapis_auth: ^0.2.12
#  google_sign_in: ^4.5.6
#  cloud_firestore: ^0.14.4
#  firebase_storage: ^5.2.0
#  google_fonts: ^1.1.1

  share: ^0.6.5
  path_provider: ^1.6.28
  open_file: ^3.0.1
#  pdf: ^1.11.2
  url_launcher: ^5.7.10
  excel: ^1.1.5
  path:
  intl: ^0.16.1
  sqflite: ^1.3.0

  flutter_icons: ^1.1.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true